#!/usr/bin/env python3
"""Build Blossom exes and optional runtime bundles.

Examples:
  py scripts/build_all.py all --stable-version 2.1.0 -o dist/2.1.0 --bootstrap
  py scripts/build_all.py runtime cv2
  py scripts/build_all.py runtime winocr
  py scripts/build_all.py runtime all
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
import zipfile
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD_INFO = ROOT / "src" / "blossom_build_info.py"
PYI_DIST = ROOT / "dist"
MANIFEST_PATH = ROOT / "assets" / "runtime_manifest.json"
WINOCR_VERSION = "0.0.15"

DEFAULT_STABLE_VERSION = "2.2.3"
DEFAULT_BETA_VERSION = "2.2.3-beta.1"
DEFAULT_BETA_EXPIRY_DAYS = 45

OBFUSCATE_MODULES = ["src/blossom_license.py"]

SPECS = {
    "stable": ("BlossomMacro.spec", "BlossomMacro"),
    "beta": ("BlossomMacro-beta.spec", "BlossomMacro-beta"),
}

BOOTSTRAP_OUTPUT = {
    "stable": "Blossom.exe",
    "beta": "Blossom-beta.exe",
}

APP_SUBDIR = "app"
LAUNCHERS_SUBDIR = "launchers"


def safe_version(version: str) -> str:
    return re.sub(r'[<>:"/\\|?*]', "-", version.strip())


def output_exe_name(_channel: str, version: str) -> str:
    return f"Blossom-{safe_version(version)}.exe"


def resolve_beta_expiry(channel: str, expiry: str | None, days: int) -> str:
    if channel != "beta":
        return ""
    if expiry:
        return expiry.strip()
    if days and days > 0:
        return (date.today() + timedelta(days=days)).isoformat()
    return ""


def resolve_watermark(channel: str, version: str, explicit: str = "") -> str:
    if channel != "beta":
        return ""
    if explicit.strip():
        return explicit.strip()
    seed = f"{version}:{time.time_ns()}"
    return hashlib.sha256(seed.encode("utf-8")).hexdigest()[:16]


def _sha256_file_quick(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().lower()


def resolve_integrity(channel: str) -> str:
    if channel != "beta":
        return ""
    parts: list[str] = []
    for rel in ("src/blossom_license.py", "src/run_local_ui.py"):
        path = ROOT / rel
        if path.is_file():
            parts.append(_sha256_file_quick(path))
    if not parts:
        return ""
    return hashlib.sha256("".join(parts).encode("utf-8")).hexdigest()[:32]


def write_build_info(
    channel: str,
    version: str,
    *,
    expiry: str = "",
    watermark: str = "",
) -> None:
    wm = resolve_watermark(channel, version, watermark)
    integrity = resolve_integrity(channel)
    BUILD_INFO.write_text(
        f'"""Generated by scripts/build_all.py — do not edit by hand."""\n\n'
        f'BUILD_CHANNEL = "{channel}"\n'
        f'APP_VERSION = "{version}"\n'
        f'BETA_EXPIRY_DATE = "{expiry}"\n'
        f'BUILD_WATERMARK = "{wm}"\n'
        f'BUILD_INTEGRITY = "{integrity}"\n',
        encoding="utf-8",
    )
    extra = f" expiry={expiry}" if expiry else ""
    extra += f" watermark={wm}" if wm else ""
    if integrity:
        extra += f" integrity={integrity[:8]}…"
    print(f"[build] blossom_build_info.py -> {channel} {version}{extra}")


def should_obfuscate(channel: str, *, no_obfuscate: bool) -> bool:
    return channel == "beta" and not no_obfuscate


def maybe_obfuscate(channel: str, enabled: bool) -> list[tuple[str, Path, Path | None]]:
    if not enabled:
        return []
    try:
        subprocess.run(
            [sys.executable, "-m", "pyarmor.cli", "--version"],
            cwd=str(ROOT),
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError):
        print("[build] WARNING: beta obfuscation requested but PyArmor is not installed; skipping.")
        return []

    out_dir = ROOT / "build" / "pyarmor"
    if out_dir.exists():
        shutil.rmtree(out_dir, ignore_errors=True)
    cmd = [
        sys.executable,
        "-m",
        "pyarmor.cli",
        "gen",
        "--output",
        str(out_dir),
        *OBFUSCATE_MODULES,
    ]
    print(f"[build] obfuscating: {' '.join(OBFUSCATE_MODULES)}")
    subprocess.run(cmd, cwd=str(ROOT), check=True)

    cleanup: list[tuple[str, Path, Path | None]] = []
    backup_dir = ROOT / "build" / "pyarmor_backup"
    backup_dir.mkdir(parents=True, exist_ok=True)
    for module in OBFUSCATE_MODULES:
        produced = out_dir / module
        target = ROOT / module
        if produced.is_file():
            backup = backup_dir / f"{module}.bak"
            shutil.copy2(target, backup)
            shutil.copy2(produced, target)
            cleanup.append(("restore", target, backup))
    for runtime in out_dir.glob("pyarmor_runtime*"):
        dest = ROOT / runtime.name
        if runtime.is_dir():
            shutil.copytree(runtime, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(runtime, dest)
        cleanup.append(("remove", dest, None))
    return cleanup


def _remove_with_retry(path: Path, attempts: int = 5) -> None:
    for attempt in range(attempts):
        try:
            if path.is_dir():
                shutil.rmtree(path)
            elif path.is_file():
                path.unlink()
            return
        except OSError:
            if attempt == attempts - 1:
                shutil.rmtree(path, ignore_errors=True)
                return
            time.sleep(0.6)


def restore_after_obfuscation(cleanup: list[tuple[str, Path, Path | None]]) -> None:
    for kind, path, backup in cleanup:
        try:
            if kind == "restore" and backup and Path(backup).is_file():
                shutil.copy2(backup, path)
            elif kind == "remove":
                _remove_with_retry(Path(path))
        except Exception as error:  # noqa: BLE001
            print(f"[build] WARNING: cleanup failed for {path}: {error}")


def resolve_out_dir(out: str | None) -> Path:
    if out:
        path = Path(out)
        if not path.is_absolute():
            path = Path.cwd() / path
        return path.resolve()
    return Path.cwd().resolve()


def app_output_dir(out: str | None) -> Path:
    path = resolve_out_dir(out) / APP_SUBDIR
    path.mkdir(parents=True, exist_ok=True)
    return path


def launchers_output_dir(out: str | None) -> Path:
    path = resolve_out_dir(out) / LAUNCHERS_SUBDIR
    path.mkdir(parents=True, exist_ok=True)
    return path


def cleanup_pyi_scratch() -> None:
    for stem in ("BlossomMacro", "BlossomMacro-beta", "Blossom", "Blossom-beta"):
        path = PYI_DIST / f"{stem}.exe"
        if path.is_file():
            try:
                path.unlink()
            except OSError:
                pass


def _copy_with_retry(src: Path, dest: Path, attempts: int = 8) -> None:
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            shutil.copy2(src, dest)
            return
        except OSError as error:
            last_error = error
            time.sleep(min(0.5 * (attempt + 1), 3.0))
    raise SystemExit(f"[build] ERROR: could not copy {src.name} -> {dest}: {last_error}")


def run_pyinstaller(
    spec_name: str,
    default_stem: str,
    *,
    env: dict[str, str] | None = None,
) -> Path:
    built = PYI_DIST / f"{default_stem}.exe"
    if built.is_file():
        try:
            built.unlink()
        except OSError as error:
            raise SystemExit(f"[build] ERROR: close {built.name} then retry: {error}") from error
    cmd = [sys.executable, "-m", "PyInstaller", spec_name, "--noconfirm"]
    print(f"[build] {' '.join(cmd)}")
    run_env = os.environ.copy()
    if env:
        run_env.update(env)
    subprocess.run(cmd, cwd=str(ROOT), check=True, env=run_env)
    if not built.is_file():
        raise SystemExit(f"[build] ERROR: missing {built}")
    return built


def build_one(
    channel: str,
    version: str,
    *,
    out: str | None,
    expiry: str = "",
    watermark: str = "",
    no_obfuscate: bool = False,
) -> Path:
    if channel not in SPECS:
        raise SystemExit(f"unknown channel {channel!r} (use stable or beta)")

    spec_name, default_stem = SPECS[channel]
    out_dir = app_output_dir(out)
    dest = out_dir / output_exe_name(channel, version)

    print(f"[build] {channel} {version} -> {dest}")
    write_build_info(channel, version, expiry=expiry, watermark=watermark)
    obfuscate = should_obfuscate(channel, no_obfuscate=no_obfuscate)
    if obfuscate:
        print("[build] PyArmor obfuscation enabled for beta license module")
    cleanup = maybe_obfuscate(channel, obfuscate)
    try:
        built = run_pyinstaller(spec_name, default_stem)
        _copy_with_retry(built, dest)
        cleanup_pyi_scratch()
    finally:
        restore_after_obfuscation(cleanup)

    size_mb = dest.stat().st_size // 1024 // 1024
    print(f"[build] OK {dest} ({size_mb} MB)")
    return dest


def build_bootstrap(
    channel: str,
    *,
    out: str | None,
    stable_version: str = DEFAULT_STABLE_VERSION,
    beta_version: str = DEFAULT_BETA_VERSION,
) -> Path:
    if channel not in BOOTSTRAP_OUTPUT:
        raise SystemExit(f"unknown bootstrap channel {channel!r}")

    out_dir = launchers_output_dir(out)
    dest = out_dir / BOOTSTRAP_OUTPUT[channel]
    default_stem = Path(BOOTSTRAP_OUTPUT[channel]).stem
    version = stable_version if channel == "stable" else beta_version

    print(f"[build] bootstrap {channel} -> {dest}")
    write_build_info(channel, version)
    built = run_pyinstaller(
        "BlossomBootstrap.spec",
        default_stem,
        env={"BOOTSTRAP_CHANNEL": channel},
    )
    _copy_with_retry(built, dest)
    cleanup_pyi_scratch()
    size_mb = dest.stat().st_size // 1024 // 1024
    print(f"[build] bootstrap OK {dest} ({size_mb} MB)")
    return dest


def push_stable_repo(version: str) -> None:
    print(f"[build] pushing source to origin (stable {version})…")
    subprocess.run(["git", "add", "-A"], cwd=ROOT, check=True)
    status = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    if status.stdout.strip():
        subprocess.run(
            ["git", "commit", "-m", f"Release stable {version}"],
            cwd=ROOT,
            check=True,
        )
    subprocess.run(["git", "push", "origin", "HEAD"], cwd=ROOT, check=True)


def _runtime_imports():
    sys.path.insert(0, str(ROOT / "src"))
    from blossom_runtime_deps import abi_key, component_archive_name, cv2_archive_name

    return abi_key, component_archive_name, cv2_archive_name


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().lower()


def _update_manifest(component_id: str, key: str, sha: str) -> None:
    try:
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        comp = manifest.setdefault("components", {}).setdefault(component_id, {})
        hashes = comp.setdefault("sha256", {})
        if isinstance(hashes, dict):
            hashes[key] = sha
            MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
            print(f"[runtime] updated {MANIFEST_PATH}")
    except (OSError, json.JSONDecodeError) as error:
        print(f"[runtime] could not auto-update manifest: {error}")


def _print_runtime_upload(name: str, archive: Path, sha: str) -> None:
    print(f"[runtime] SHA-256: {sha}")
    print("[runtime] upload to blossombeta release tag runtime-deps:")
    print(f"          asset: {name}")
    print(f"          file:  {archive}")


def build_runtime_cv2() -> int:
    try:
        import cv2  # type: ignore
    except ImportError:
        print("[runtime] ERROR: cv2 not installed (pip install opencv-python)")
        return 1

    abi_key, _, cv2_archive_name = _runtime_imports()
    cv2_pkg = Path(cv2.__file__).resolve().parent
    if cv2_pkg.name != "cv2":
        print(f"[runtime] ERROR: unexpected cv2 location: {cv2_pkg}")
        return 1

    key = abi_key()
    out_dir = ROOT / "dist" / "runtime"
    out_dir.mkdir(parents=True, exist_ok=True)
    archive = out_dir / cv2_archive_name(key)
    if archive.exists():
        archive.unlink()

    file_count = 0
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in sorted(cv2_pkg.rglob("*")):
            if path.is_file():
                arcname = "cv2/" + str(path.relative_to(cv2_pkg)).replace("\\", "/")
                zf.write(path, arcname)
                file_count += 1

    sha = _sha256_file(archive)
    size_mb = archive.stat().st_size / 1024 / 1024
    print(f"[runtime] cv2 ABI={key} files={file_count} size={size_mb:.1f} MB")
    _update_manifest("cv2", key, sha)
    _print_runtime_upload(archive.name, archive, sha)
    return 0


def _ensure_winocr() -> None:
    try:
        import winocr  # type: ignore  # noqa: F401
    except ImportError:
        print(f"[runtime] installing winocr=={WINOCR_VERSION} …")
        subprocess.run(
            [sys.executable, "-m", "pip", "install", f"winocr=={WINOCR_VERSION}"],
            check=True,
        )


def _winocr_archive_entries() -> list[tuple[Path, str]]:
    import winocr  # type: ignore

    entries: list[tuple[Path, str]] = []
    winocr_file = Path(winocr.__file__).resolve()
    site_packages = winocr_file.parent

    if winocr_file.name == "winocr.py":
        entries.append((winocr_file, "winocr/__init__.py"))
    elif winocr_file.parent.name == "winocr":
        winocr_pkg = winocr_file.parent
        for path in sorted(winocr_pkg.rglob("*")):
            if path.is_file():
                rel = path.relative_to(winocr_pkg)
                entries.append((path, f"winocr/{rel.as_posix()}"))
    else:
        print(f"[runtime] ERROR: unexpected winocr location: {winocr_file}")
        return []

    for child in sorted(site_packages.iterdir()):
        name = child.name.lower()
        if child.is_dir() and (name == "winrt" or name.startswith("winrt_")):
            top_name = child.name
            for path in sorted(child.rglob("*")):
                if path.is_file():
                    rel = path.relative_to(child)
                    entries.append((path, f"{top_name}/{rel.as_posix()}"))
    return entries


def build_runtime_winocr() -> int:
    _ensure_winocr()
    entries = _winocr_archive_entries()
    if not entries:
        print("[runtime] ERROR: no winocr/winrt packages found")
        return 1

    abi_key, component_archive_name, _ = _runtime_imports()
    key = abi_key()
    out_dir = ROOT / "dist" / "runtime"
    out_dir.mkdir(parents=True, exist_ok=True)
    archive = out_dir / component_archive_name("winocr", key)
    if archive.exists():
        archive.unlink()

    file_count = 0
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for source, arcname in entries:
            zf.write(source, arcname)
            file_count += 1

    sha = _sha256_file(archive)
    size_mb = archive.stat().st_size / 1024 / 1024
    print(f"[runtime] winocr ABI={key} files={file_count} size={size_mb:.1f} MB")
    _update_manifest("winocr", key, sha)
    _print_runtime_upload(archive.name, archive, sha)
    return 0


def build_runtime(component: str) -> int:
    if component == "cv2":
        return build_runtime_cv2()
    if component == "winocr":
        return build_runtime_winocr()
    if component == "all":
        code = build_runtime_cv2()
        if code != 0:
            return code
        return build_runtime_winocr()
    raise SystemExit(f"unknown runtime component {component!r} (use cv2, winocr, or all)")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build Blossom exes and runtime bundles")
    parser.add_argument(
        "target",
        nargs="?",
        choices=("stable", "beta", "all", "runtime"),
        default="all",
    )
    parser.add_argument(
        "version",
        nargs="?",
        help="Version for stable/beta builds, or runtime component (cv2, winocr, all)",
    )
    parser.add_argument("-o", "--out", help="Output folder (default: current directory)")
    parser.add_argument("--stable-version", default=DEFAULT_STABLE_VERSION)
    parser.add_argument("--beta-version", default=DEFAULT_BETA_VERSION)
    parser.add_argument("--beta-expiry", default="")
    parser.add_argument("--beta-expiry-days", type=int, default=DEFAULT_BETA_EXPIRY_DAYS)
    parser.add_argument("--watermark", default="", help="Beta build stamp (auto-generated if omitted)")
    parser.add_argument(
        "--no-obfuscate",
        action="store_true",
        help="Skip PyArmor on beta (obfuscation is on by default for beta)",
    )
    parser.add_argument("--push-repo", action="store_true")
    parser.add_argument("--bootstrap", action="store_true")
    parser.add_argument("--bootstrap-only", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    if args.target == "runtime":
        component = args.version or "all"
        if component not in ("cv2", "winocr", "all"):
            print("[build] ERROR: runtime needs cv2, winocr, or all")
            return 1
        return build_runtime(component)

    PYI_DIST.mkdir(parents=True, exist_ok=True)
    beta_expiry = resolve_beta_expiry("beta", args.beta_expiry, args.beta_expiry_days)

    if args.target == "all":
        out = str(resolve_out_dir(args.out)) if args.out else str(PYI_DIST.resolve())
        if not args.bootstrap_only:
            build_one("stable", args.stable_version, out=out)
            build_one(
                "beta",
                args.beta_version,
                out=out,
                expiry=beta_expiry,
                watermark=args.watermark,
                no_obfuscate=args.no_obfuscate,
            )
        if args.bootstrap or args.bootstrap_only:
            build_bootstrap("stable", out=out, stable_version=args.stable_version, beta_version=args.beta_version)
            build_bootstrap("beta", out=out, stable_version=args.stable_version, beta_version=args.beta_version)
        root = resolve_out_dir(out)
        print(f"[build] Done — payload: {root / APP_SUBDIR}  launchers: {root / LAUNCHERS_SUBDIR}")
        return 0

    if not args.version:
        print("[build] ERROR: pass a version for stable/beta builds")
        return 1

    expiry = resolve_beta_expiry(args.target, args.beta_expiry, args.beta_expiry_days)
    if not args.bootstrap_only:
        build_one(
            args.target,
            args.version,
            out=args.out,
            expiry=expiry,
            watermark=args.watermark,
            no_obfuscate=args.no_obfuscate,
        )
    if args.bootstrap or args.bootstrap_only:
        build_bootstrap(
            args.target,
            out=args.out,
            stable_version=args.version if args.target == "stable" else args.stable_version,
            beta_version=args.version if args.target == "beta" else args.beta_version,
        )
    if args.target == "stable" and args.push_repo:
        push_stable_repo(args.version)
    if args.out:
        root = resolve_out_dir(args.out)
        print(f"[build] Done — payload: {root / APP_SUBDIR}  launchers: {root / LAUNCHERS_SUBDIR}")
    else:
        print("[build] Done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
