#!/usr/bin/env python3
"""Build Blossom exes → Blossom-{version}.exe (version only, no repeated channel words).

Examples:
  py scripts/build_all.py all --stable-version 2.0.0 -o dist/2.0.0
      → Blossom-2.0.0.exe, Blossom-2.1.0-beta.1.exe
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD_INFO = ROOT / "src" / "blossom_build_info.py"
PYI_DIST = ROOT / "dist"

DEFAULT_STABLE_VERSION = "2.0.0"
DEFAULT_BETA_VERSION = "2.1.0-beta.1"
# How long a beta build stays usable when no explicit expiry date is given.
DEFAULT_BETA_EXPIRY_DAYS = 45

# Modules obfuscated by PyArmor when --obfuscate is passed (beta only).
# Kept to the license/gate module so the free PyArmor trial can handle it; the
# trial refuses larger files ("out of license"). With a paid PyArmor license you
# can add heavier modules like "macro_engine.py" here too.
OBFUSCATE_MODULES = ["src/blossom_license.py"]

SPECS = {
    "stable": ("BlossomMacro.spec", "BlossomMacro"),
    "beta": ("BlossomMacro-beta.spec", "BlossomMacro-beta"),
}

def safe_version(version: str) -> str:
    return re.sub(r'[<>:"/\\|?*]', "-", version.strip())


def output_exe_name(_channel: str, version: str) -> str:
    return f"Blossom-{safe_version(version)}.exe"


def resolve_beta_expiry(channel: str, expiry: str | None, days: int) -> str:
    if channel != "beta":
        return ""
    if expiry:
        return expiry.strip()
    if days and days > 0:
        return (date.today() + timedelta(days=days)).isoformat()
    return ""


def write_build_info(
    channel: str,
    version: str,
    *,
    expiry: str = "",
    watermark: str = "",
) -> None:
    wm = watermark if channel == "beta" else ""
    BUILD_INFO.write_text(
        f'"""Generated by scripts/build_all.py — do not edit by hand."""\n\n'
        f'BUILD_CHANNEL = "{channel}"\n'
        f'APP_VERSION = "{version}"\n'
        f'BETA_EXPIRY_DATE = "{expiry}"\n'
        f'BUILD_WATERMARK = "{wm}"\n',
        encoding="utf-8",
    )
    extra = f" expiry={expiry}" if expiry else ""
    extra += f" watermark={wm}" if wm else ""
    print(f"[build] blossom_build_info.py -> {channel} {version}{extra}")


def maybe_obfuscate(channel: str, enabled: bool) -> list[tuple[str, Path, Path | None]]:
    """Best-effort PyArmor obfuscation of the license/gate module (beta only).

    Opt-in via --obfuscate. Skipped (with a warning) if PyArmor is missing, so a
    normal build never breaks. Obfuscated files overwrite the originals in-place
    before PyInstaller runs; this returns a cleanup plan so build_one() can
    restore your source tree afterwards (originals are backed up first).
    """
    if not enabled or channel != "beta":
        return []
    try:
        subprocess.run(
            [sys.executable, "-m", "pyarmor.cli", "--version"],
            cwd=str(ROOT),
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError):
        print("[build] WARNING: --obfuscate requested but PyArmor is not installed; skipping.")
        print("[build]          install with:  py -m pip install pyarmor")
        return []

    out_dir = ROOT / "build" / "pyarmor"
    if out_dir.exists():
        shutil.rmtree(out_dir, ignore_errors=True)
    cmd = [
        sys.executable,
        "-m",
        "pyarmor.cli",
        "gen",
        "--output",
        str(out_dir),
        *OBFUSCATE_MODULES,
    ]
    print(f"[build] obfuscating: {' '.join(OBFUSCATE_MODULES)}")
    subprocess.run(cmd, cwd=str(ROOT), check=True)

    cleanup: list[tuple[str, Path, Path | None]] = []
    backup_dir = ROOT / "build" / "pyarmor_backup"
    backup_dir.mkdir(parents=True, exist_ok=True)
    for module in OBFUSCATE_MODULES:
        produced = out_dir / module
        target = ROOT / module
        if produced.is_file():
            backup = backup_dir / f"{module}.bak"
            shutil.copy2(target, backup)
            shutil.copy2(produced, target)
            cleanup.append(("restore", target, backup))
            print(f"[build] swapped obfuscated {module} into place")
    for runtime in out_dir.glob("pyarmor_runtime*"):
        dest = ROOT / runtime.name
        if runtime.is_dir():
            shutil.copytree(runtime, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(runtime, dest)
        cleanup.append(("remove", dest, None))
        print(f"[build] copied {runtime.name} runtime into project root")
    return cleanup


def _remove_with_retry(path: Path, attempts: int = 5) -> None:
    """Remove a file/dir, retrying briefly to dodge Windows file-in-use locks
    (AV scanners / just-released native handles raise WinError 32)."""
    import time

    for attempt in range(attempts):
        try:
            if path.is_dir():
                shutil.rmtree(path)
            elif path.is_file():
                path.unlink()
            return
        except OSError:
            if attempt == attempts - 1:
                shutil.rmtree(path, ignore_errors=True)
                return
            time.sleep(0.6)


def restore_after_obfuscation(cleanup: list[tuple[str, Path, Path | None]]) -> None:
    """Undo maybe_obfuscate's in-place swaps so the source tree is left clean.

    Runs best-effort and never raises: it executes after the build has already
    produced the exe, so a transient Windows lock must not fail the whole build.
    """
    for kind, path, backup in cleanup:
        try:
            if kind == "restore" and backup and Path(backup).is_file():
                shutil.copy2(backup, path)
                print(f"[build] restored original {Path(path).name}")
            elif kind == "remove":
                _remove_with_retry(Path(path))
                print(f"[build] removed build artifact {Path(path).name}")
        except Exception as error:  # noqa: BLE001 - cleanup must never fail the build
            print(f"[build] WARNING: cleanup failed for {path}: {error}")


def resolve_out_dir(out: str | None) -> Path:
    if out:
        path = Path(out)
        if not path.is_absolute():
            path = Path.cwd() / path
        return path.resolve()
    return Path.cwd().resolve()


def cleanup_pyi_scratch() -> None:
    for stem in ("BlossomMacro", "BlossomMacro-beta"):
        path = PYI_DIST / f"{stem}.exe"
        if path.is_file():
            try:
                path.unlink()
            except OSError:
                pass


def _copy_with_retry(src: Path, dest: Path, attempts: int = 8) -> None:
    """Copy the freshly-built exe, retrying past transient Windows file locks.

    Antivirus often scans a just-written .exe and briefly holds it open, which
    surfaces as PermissionError/WinError 32 on CopyFile2. Retry with backoff.
    """
    import time

    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            shutil.copy2(src, dest)
            return
        except OSError as error:
            last_error = error
            wait = min(0.5 * (attempt + 1), 3.0)
            print(f"[build] copy locked (attempt {attempt + 1}/{attempts}); retrying in {wait:.1f}s")
            time.sleep(wait)
    raise SystemExit(f"[build] ERROR: could not copy {src.name} -> {dest}: {last_error}")


def run_pyinstaller(spec_name: str, default_stem: str) -> Path:
    built = PYI_DIST / f"{default_stem}.exe"
    if built.is_file():
        try:
            built.unlink()
        except OSError as error:
            print(f"[build] ERROR: close {built.name} then retry: {error}")
            raise SystemExit(1) from error
    cmd = [sys.executable, "-m", "PyInstaller", spec_name, "--noconfirm"]
    print(f"[build] {' '.join(cmd)}")
    subprocess.run(cmd, cwd=str(ROOT), check=True)
    if not built.is_file():
        raise SystemExit(f"[build] ERROR: missing {built}")
    return built


def build_one(
    channel: str,
    version: str,
    *,
    out: str | None,
    expiry: str = "",
    watermark: str = "",
    obfuscate: bool = False,
) -> Path:
    if channel not in SPECS:
        raise SystemExit(f"unknown channel {channel!r} (use stable or beta)")

    spec_name, default_stem = SPECS[channel]
    out_dir = resolve_out_dir(out)
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / output_exe_name(channel, version)

    print(f"[build] {channel} {version} -> {dest}")

    write_build_info(channel, version, expiry=expiry, watermark=watermark)
    cleanup = maybe_obfuscate(channel, obfuscate)
    try:
        built = run_pyinstaller(spec_name, default_stem)
        _copy_with_retry(built, dest)
        cleanup_pyi_scratch()
    finally:
        restore_after_obfuscation(cleanup)

    print(f"[build] GitHub upload name: {dest.name}")

    size_mb = dest.stat().st_size // 1024 // 1024
    print(f"[build] OK {dest} ({size_mb} MB)")
    return dest


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build BlossomMacro exe(s)")
    parser.add_argument("target", nargs="?", choices=("stable", "beta", "all"), default="all")
    parser.add_argument("version", nargs="?", help="Version (required for stable/beta)")
    parser.add_argument("-o", "--out", help="Output folder (default: current directory)")
    parser.add_argument("--stable-version", default=DEFAULT_STABLE_VERSION)
    parser.add_argument("--beta-version", default=DEFAULT_BETA_VERSION)
    parser.add_argument(
        "--beta-expiry",
        default="",
        help="Beta expiry date YYYY-MM-DD (default: today + --beta-expiry-days)",
    )
    parser.add_argument("--beta-expiry-days", type=int, default=DEFAULT_BETA_EXPIRY_DAYS)
    parser.add_argument(
        "--watermark",
        default="",
        help="Per-tester id embedded in the beta build for leak tracing",
    )
    parser.add_argument(
        "--obfuscate",
        action="store_true",
        help="Obfuscate license modules with PyArmor before building (beta only)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    PYI_DIST.mkdir(parents=True, exist_ok=True)

    beta_expiry = resolve_beta_expiry("beta", args.beta_expiry, args.beta_expiry_days)

    if args.target == "all":
        out = str(resolve_out_dir(args.out)) if args.out else str(PYI_DIST.resolve())
        build_one("stable", args.stable_version, out=out)
        build_one(
            "beta",
            args.beta_version,
            out=out,
            expiry=beta_expiry,
            watermark=args.watermark,
            obfuscate=args.obfuscate,
        )
        print(f"[build] Done — see {out}")
        return 0

    if not args.version:
        print(
            "[build] ERROR: pass a version, e.g.  cd dist\\1.5.5  then  "
            "py ..\\..\\scripts\\build_all.py stable 1.5.5"
        )
        return 1

    expiry = resolve_beta_expiry(args.target, args.beta_expiry, args.beta_expiry_days)
    build_one(
        args.target,
        args.version,
        out=args.out,
        expiry=expiry,
        watermark=args.watermark,
        obfuscate=args.obfuscate,
    )
    print("[build] Done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
